# <mamba or conda> env create -f environment_cross_platform.yml
# try mamba first, it's faster and safe. It if fails (`Could not find a version...`), use conda. 
# Except, errors about 'pdgpy3dtiles' are expected! Must be installed manually.. Still under dev.
name: full_viz_pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas-base=0.10.2
  - geopandas=0.10.2
  - numba=0.55.1
  - pyzmq=22.3.0
  - python=3.9.12
  - pthread-stubs=0.4
  - libzip=1.8.0
  - pip=22.0.4
  - numpy=1.20.3
  - libblas=3.9.0
  - fiona=1.8.21
  - six=1.16.0
  - click-plugins=1.1.1
  - attrs=21.4.0
  - pytz=2022.1
  - python-dateutil=2.8.2
  - click=8.0.4
  - liblapack=3.9.0
  - pcre=8.45
  - psycopg2-binary=2.9.3
  - libcblas=3.9.0
  - cligj=0.7.2
  - psutil=5.9.0
  - psycopg2=2.9.3
  - libllvm11=11.1.0
  - pycparser=2.21
  - certifi=2021.10.8
  - pyproj=3.3.0
  - munch=2.5.0
  - pillow=9.1.0
  - llvmlite=0.38.0
  - cython=0.29.28
  - libopenblas=0.3.20
  - lz4=4.0.0
  - pandas=1.4.1
  - llvm-openmp=13.0.1
  - pip:
    - affine==2.3.1
    - aiohttp==3.8.1
    - aiohttp-cors==0.7.0
    - aiosignal==1.2.0
    - async-timeout==4.0.2
    - blessed==1.19.1
    - cachetools==5.1.0
    - coloraide==0.18.1
    - colorful==0.5.4
    - distlib==0.3.4
    - filelock==3.7.0
    - frozenlist==1.3.0
    - google-api-core==2.7.3
    - google-auth==2.6.6
    - googleapis-common-protos==1.56.1
    - gpustat==1.0.0b1
    - grpcio==1.43.0
    - jsonschema==4.5.1
    - morecantile==3.1.2
    - msgpack==1.0.3
    - multidict==6.0.2
    - numpy==1.20.3
    - nvidia-ml-py3==7.352.0
    - opencensus==0.9.0
    - opencensus-context==0.1.2
    - pdgpy3dtiles
    - pdgraster==0.1.0
    - pdgstaging==0.1.0
    - platformdirs==2.5.2
    - prometheus-client==0.13.1
    - protobuf==3.20.1
    - py-spy==0.3.11
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.9.0
    - pyrsistent==0.18.1
    - pyyaml==6.0
    - rasterio==1.2.10
    - ray==1.12.0
    - rsa==4.8
    - rtree==0.9.7
    - smart-open==6.0.0
    - snuggs==1.4.7
    - triangle==20200424
    - typing-extensions==4.2.0
    - virtualenv==20.14.1
    - viz-3dtiles==0.0.1
    - wcwidth==0.2.5
    - yarl==1.7.2
